"""Load and validate a screenplay scene map.

The scene map is produced by an external tool and is *not* generated by this pipeline.
That independence matters: coverage in ``checks.py`` grades against this list, and a list
this pipeline produced would measure compliance rather than correctness.

Every offset is validated against the scene's own recorded anchor before any text is
sliced. A sibling project sliced a raw file with offsets computed over cleaned text; 13 of
15 scenes never reached the model, and the metric could not see it because it compared
against the same corrupted slice. ``load_scenes`` refuses to return on that failure.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional


HEAD_SCENE_ID = "sc-000"


@dataclass(frozen=True)
class Scene:
    scene_id: str
    index: int
    heading_raw: str
    kind: str
    location: str
    time_of_day: Optional[str]
    start_char: int
    end_char: int
    word_count: int
    speakers: List[str] = field(default_factory=list)

    def text(self, source: str) -> str:
        return source[self.start_char : self.end_char]


class SceneMapError(RuntimeError):
    """Raised when a scene map cannot be trusted against its source text."""


def _norm(value: str) -> str:
    return " ".join(value.split())


def load_source(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def source_digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def load_scenes(
    map_path: Path,
    source: str,
    *,
    anchor_prefix: int = 25,
    include_head: bool = True,
) -> List[Scene]:
    """Return scenes in source order, after validating every offset against its anchor.

    ``include_head`` attaches the material before the first slugline (title block and the
    opening pre-slugline sequence) as a synthetic ``sc-000``. It is real content, so
    dropping it would silently lose facts while every coverage check still passed.
    """
    payload = json.loads(map_path.read_text(encoding="utf-8"))
    raw_scenes = payload["scenes"]

    declared = payload.get("source_chars")
    if declared is not None and declared != len(source):
        raise SceneMapError(
            "scene map was built against a different text: map says {} chars, source has {}".format(
                declared, len(source)
            )
        )

    scenes: List[Scene] = []
    failures: List[str] = []
    for scene_id, entry in raw_scenes.items():
        start, end = int(entry["start_char"]), int(entry["end_char"])
        if not (0 <= start < end <= len(source)):
            failures.append("{}: offsets {}..{} outside source".format(scene_id, start, end))
            continue
        segment = source[start:end]

        expected_start = _norm(entry.get("start_quote", ""))[:anchor_prefix]
        if expected_start and not _norm(segment).startswith(expected_start):
            failures.append("{}: text at offset does not match start anchor".format(scene_id))
        expected_end = _norm(entry.get("end_quote", ""))[-anchor_prefix:]
        if expected_end and expected_end not in _norm(segment):
            failures.append("{}: text at offset does not match end anchor".format(scene_id))

        scenes.append(
            Scene(
                scene_id=scene_id,
                index=int(entry["index"]),
                heading_raw=entry.get("heading", ""),
                kind=entry.get("kind", ""),
                location=entry.get("location", ""),
                time_of_day=entry.get("time_of_day"),
                start_char=start,
                end_char=end,
                word_count=int(entry.get("word_count", len(segment.split()))),
                speakers=list(entry.get("speakers") or []),
            )
        )

    if failures:
        raise SceneMapError(
            "{} of {} scenes failed anchor validation; refusing to slice:\n  {}".format(
                len(failures), len(raw_scenes), "\n  ".join(failures[:10])
            )
        )

    scenes.sort(key=lambda scene: scene.start_char)
    _assert_disjoint(scenes)

    if include_head and scenes and scenes[0].start_char > 0:
        head_text = source[: scenes[0].start_char]
        if head_text.strip():
            scenes.insert(
                0,
                Scene(
                    scene_id=HEAD_SCENE_ID,
                    index=0,
                    heading_raw="[pre-slugline opening]",
                    kind="PRE",
                    location="",
                    time_of_day=None,
                    start_char=0,
                    end_char=scenes[0].start_char,
                    word_count=len(head_text.split()),
                    speakers=sorted(set(re.findall(r"^\s*([A-Z][A-Z .'#-]{2,})\s*$", head_text, re.M))),
                ),
            )
    return scenes


def _assert_disjoint(scenes: List[Scene]) -> None:
    for earlier, later in zip(scenes, scenes[1:]):
        if earlier.end_char > later.start_char:
            raise SceneMapError(
                "scenes {} and {} overlap ({} > {})".format(
                    earlier.scene_id, later.scene_id, earlier.end_char, later.start_char
                )
            )


def attribution_report(scenes: List[Scene], source: str) -> Dict[str, object]:
    """Report how much of the source belongs to a scene, and where the gaps are."""
    covered = sum(scene.end_char - scene.start_char for scene in scenes)
    gaps = []
    cursor = 0
    for scene in scenes:
        if scene.start_char > cursor:
            gaps.append({"start": cursor, "end": scene.start_char, "chars": scene.start_char - cursor})
        cursor = max(cursor, scene.end_char)
    if cursor < len(source):
        gaps.append({"start": cursor, "end": len(source), "chars": len(source) - cursor})
    return {
        "scenes": len(scenes),
        "source_chars": len(source),
        "covered_chars": covered,
        "coverage": round(covered / len(source), 4) if source else 0.0,
        "gap_count": len(gaps),
        "gap_chars": sum(int(gap["chars"]) for gap in gaps),
        "gaps": gaps[:20],
    }


def scene_index_listing(scenes: List[Scene]) -> str:
    """A compact id -> heading table, so an agent never has to invent a scene id."""
    return "\n".join(
        "{}  [{} w]  {}".format(scene.scene_id, scene.word_count, scene.heading_raw or "(no heading)")
        for scene in scenes
    )
